config create:
  dbhost: mysql
  dbuser: wordpress
  dbpass: password
  path: /var/www/html/src
  extra-php: |
    define( 'DISALLOW_FILE_EDIT', true );
    define( 'WP_DEBUG', true );
    define( 'SAVEQUERIES', true );
    define( 'EP_HOST', 'http://elasticsearch:9200' );
